### ISSUE TITLE
Unable to load when reverse proxy is configured with a location other than root

### ISSUE THREAD

**Issue by pabpas** [getAlby/hub#1025]
First time trying Alby Hub and I noticed that if I serve it (with nginx) to the outside in `mydomain.com/alby`, the browser will show an error about `malformed jwt` and the main page will not load. Setting the location to / solves the issue (`mydomain.com/`).

**Comment by rolznz** [comment]
Hi, yeah unfortunately I don't think it will work not on the route. `alby.mydomain.com` would work if you are ok with adding another DNS entry

**Comment by daum3ns** [comment]
i am confused because my redirect removes the URI. This is also visible in the AlbyHub logs 

`{"host":"removed","level":"info","msg":"handled API request","remote_ip":"xx.xx.xx.xx","request_id":"wfkXCdKaybzbrkeZKxviGvMBrPjDpqAw","status":200,"time":"2025-02-23T11:58:28Z","uri":"/","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0"}`

as you can see the URI is /, the status code is 200, but the page is just blank.. No indication of an error in the logs.. 
when i do a request to the /api  i get the same "missing or malformed jwt"" error as pabpas

**Comment by rolznz** [comment]
Hi, what version are you running? did you start/unlock Alby Hub?

**Comment by daum3ns** [comment]
HI
I use the latest version from github (v1.14.3). No I just started the binary and wanted to access the site but only see a white page. However, i just realized that, when I make a call to the correct port und using plain HTTP (i.e without going through the proxy) i can see the page. 
Do you think i need to go through a set up process of some kind before it can work (i'm new to albyhub)?

**Comment by rolznz** [comment]
@daum3ns what error code do you get on the white page? did you setup the proxy correctly for https and correctly configure your subdomain?

**Comment by daum3ns** [comment]
let me try to explain better :) my idea was that the reverse proxy (nginx) terminates the tls connection. 
i have the following start script for albyhub:

```bash
#!/bin/bash

WORK_DIR="/mnt/opt/albyhub/data" LOG_EVENTS=true LDK_GOSSIP_SOURCE="" PORT="8029" LN_BACKEND_TYPE=LND LND_ADDRESS=127.0.0.1:10019 LND_CERT_FILE=<path_to_cert> LND_MACAROON_FILE=<path_to_macaroon> /mnt/opt/albyhub/bin/albyhub
```

and in the nginx configuration i have defined a backend :
```
upstream albyhub {
  server 127.0.0.1:8029;
}

```

and a proxypass directive, to route everything under /albyhub/ to the backend: 
```
  location ^~ /albyhub/ {
    proxy_pass http://albyhub/;
  }

```
this results in a 200 on first request, but then a bunch of 502's
![Image](https://github.com/user-attachments/assets/05dcf033-a01f-44b1-a10c-241ad1614034)

in comparison, when i browse the port directly (and without https) it seems to work: 

![Image](https://github.com/user-attachments/assets/700f559d-084b-49af-a0bf-643748c4c13b)


I can't do this via subdomain unfortunately...

**Comment by daum3ns** [comment]
i think i just figured it out... if i make a call to the .js file (which fails to load in screenshot 1) manually, and add the /albyhub/ path in front, i can fetch it.... 

![Image](https://github.com/user-attachments/assets/b7d9b75c-8978-40ad-a057-b4465bc2d44c)

so albyhub responds with "please load the file from /<path>" but this should be translated to "please load /albyhub/<path>" in my case... i will check if i can achieve this in nginx proxy...

**Comment by daum3ns** [comment]
seems to be hard to solve this in nginx... i would have to rewrite the responses from albyhub to include the path prefix... 

i tried setting both BASE_URL and FRONTEND_URL env vars, but from what i can tell from looking at the code this is only used for oauth redirects... 

a setting like PATH_PREFIX or something would be really nice, if it is set, albyhub just always puts it in front of the uri... 

could this be added in this line here?

https://github.com/getAlby/hub/blob/3e1d16d4232fad8f28abb5402b3b3a4fe6a79893/frontend/src/components/redirects/DefaultRedirect.tsx#L23

**Comment by rolznz** [comment]
@daum3ns I think several changes need to be made to make it work properly and a bit more complex configuration, which I would try to avoid unless really necessary. Just to understand better, why can't you use a subdomain?

**Comment by daum3ns** [comment]
I am working on the integration of albyhub for the NODL (https://www.nodl.eu/)
at the moment I am developing this in a cloud instance. I don't have access to the DNS entries there, customers get their subdomain and can then access there cloud nodl.. 
However, in the end it should run on the devices, they are at home and there is no external access.. (except via tor)
How do other nodes do this? 
Maybe I can do it by going on a different port ...

**Comment by rolznz** [comment]
@daum3ns for self-hosting, Start9 and Umbrel give different .local addresses too.

For nodl cloud using a different port could be good to try, since it wouldn't require any changes on Alby Hub's end. But please let me know if that doesn't work for you.

**Comment by daum3ns** [comment]
i got in contact with the nodl team:

> Using another port is not a good solution as many places (corporate proxies, public networks, …) block HTTP on non standard ports.

> Another issue is that for the cloud instances, we can easily map multiple subdomains on a server but with mDNS (.local addresses) it’s non-trivial and not well supported by clients. 

i will have a look at the code, maybe i can contribute when i find time, so that we can get it running on a subpath ...

**Comment by rolznz** [comment]
@daum3ns how does nodl cloud work right now? do all their different apps run on different subpaths?

**Comment by daum3ns** [comment]
yes exactly, for example ride the lightning is at /rtl , the bitcoin rpc explorer at /btc-rpc-explorer and so on.. 
i know that btcpay-server is an exception but that seems to lead to problems sometimes...

**Comment by rolznz** [comment]
@daum3ns I think as long as this doesn't complicate the code too much maybe it's worthwhile to add. If you are able to do a PR that's easily testable (e.g. would we need a run nginx or caddy locally with a basic config to test it?) that would be great!

Let me know if you get stuck or need any help.

**Comment by daum3ns** [comment]
I think I have a nice testing setup locally, this is what I do:
1. build the http binary:
`go1.23.7 build -o main cmd/http/main.go`
`cp main tmp/`
2. run the frontend:
`cd frontend/`
`yarn dev:http --host`
3. in another shell, run the http binary:
`cd tmp/`
`./main`
4. in a third shell, run [envoy](https://github.com/envoyproxy/envoy) using [func-e](https://github.com/tetratelabs/func-e)
`func-e run -c envoy.yaml`
5. access albyhub via browser

i have two envoy configurations that show the problem: 
envoy.yaml (works)

``` yaml
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 127.0.0.1, port_value: 80 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: some_service }
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: some_service
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: some_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 5173
```
envoy-sub.yaml (fails)


``` yaml
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 127.0.0.1, port_value: 80 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/albyhub" }
                route: { cluster: some_service }
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: some_service
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: some_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 5173
```
the only difference in the configuration is the route

![Image](https://github.com/user-attachments/assets/d068d8f1-6a0f-450c-b0d4-bbfc6aaafb83)


however, I still need to figure out a lot how it works internally..  😄
