### ISSUE TITLE
Docker image tag latest is not valid

### ISSUE THREAD

**Issue by iBobik** [getAlby/hub#1192]
When I try to use Docker image tag latest ([as suggested](https://github.com/getAlby/hub/blob/master/docker-compose.yml#L5)) it will fail:
```
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 
```

When I specify the version it will download correct platform:
```
services:
  albyhub:
    container_name: albyhub
    image: ghcr.io/getalby/hub:v1.14.3
```
But this will not auto update the image.

**Comment by rolznz** [comment]
Hi,

I think it's not actually the version, but that the docker compose file does not support arm (see line 3: `platform: linux/amd64`)

Did you already remove that line and now it works? maybe you can just try put `latest` rather than `v1.14.3`?

The docker image we build is multiplatform.

**Comment by iBobik** [comment]
Hi,
I does not use platform key in my compose file.

17. 3. 2025 6:12:50, Roland ***@***.***> napsal:

**Comment by iBobik** [comment]
Btw, latest tag seems to target to the latest commit in the master branch, which is not usual for the Docker images, so confusing.

In Docker world it is usual to have this tags: 
- v1.15.0 -> tagged release
- latest -> latest tagged release
- dev -> latest commit in master branch

**Comment by rolznz** [comment]
Does it work now with `image: ghcr.io/getalby/hub:latest`?

**Comment by iBobik** [comment]
I added platform and now it works:
```
services:
  albyhub:
    image: ghcr.io/getalby/hub:latest
    platform: linux/arm64/v8
```

It is good to mention it in the example docker-compose.yml, isn’t it?
